version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x

  pre_build:
    commands:
      - cd $CODEBUILD_SRC_DIR/cicd # Change directory to the cicd folder
      - chmod +x install-terraform.sh configure-named-profile.sh apply-terraform.sh # Make files executable
      - ./install-terraform.sh # Install Terraform
      - ./configure-named-profile.sh # Configure named profile

  build:
    commands:
      - ./apply-terraform.sh # Execute Terraform apply
