version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x

  pre_build:
    commands:
      - cd terraform-projects-2.0 # Change directory to the root directory
      - cd cicd # Navigate to the cicd directory
      - chmod +x install-terraform.sh configure-named-profile.sh apply-terraform.sh # Make files executable
      - ./install-terraform.sh # Install Terraform
      - ./configure-named-profile.sh # Configure named profile

  build:
    commands:
      - ./apply-terraform.sh # Execute Terraform apply
